import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Navbar from './Navbar';
import React, { ReactNode } from "react";
import twitter from '../../public/icon/twitter.svg'
import facebook from '../../public/icon/facebook.svg'
import instagram from '../../public/icon/instagram.svg'
import github from '../../public/icon/github.svg'
import linkedin from '../../public/icon/linkedin.svg'
import email from '../../public/icon/email.svg'
import personalBlog from '../../public/icon/personal-blog.svg'
import Image from 'next/image';

interface Props {
    children?: ReactNode
    title: string
}

export default function Layout({ children, ...props }: Props) {
  const mediaSocial = [
    { 
      name: 'Twitter',
      src: twitter,
      url: 'https://twitter.com/ismynr',
    },
    { 
      name: 'Email',
      src: email,
      url: 'mailto:isminururrizqi.nr@gmail.com',
    },
    { 
      name: 'Github',
      src: github,
      url: 'https://github.com/ismynr',
    },
    { 
      name: 'Personal Blog',
      src: personalBlog,
      url: 'https://ismynr.xyz',
    },
    { 
      name: 'Linkedin',
      src: linkedin,
      url: 'https://linkedin.com/in/ismynr',
    },
    { 
      name: 'Facebook',
      src: facebook,
      url: '#',
    },
    { 
      name: 'Instagram',
      src: instagram,
      url: 'https://www.instagram.com/ismynr.xyz/',
    },
  ]
  return (
    <div>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
     
      <main className={styles.main} style={{minHeight: "70vh"}}>
        {children}
      </main>

      <footer className="footer footer-center p-10 bg-primary text-primary-content">
        <div>
          <div className="grid grid-flow-col gap-5">
            {mediaSocial.map((item) => (
              <>
                <a className="tooltip" data-tip={item.name} href={item.url} target="_blank" rel="noreferrer">
                  <Image
                    src={item.src}
                    width={24}
                    height={24}
                    alt={item.name}
                  />
                </a>
              </>
            ))}
          </div>
        </div> 
        <div>
          <p> Made with <br /> Typescript ◆ Next.js ◆ Tailwind ◆ daisyUI <br /><br /> <b>Copyright © 2023</b></p>
        </div>
      </footer>
    </div>
  )
}
